task_sshd and task_restore_root_home & task_restore_user refactored

diff --git a/bin/restore-ish b/bin/restore-ish
--- a/bin/restore-ish
+++ b/bin/restore-ish
@@ -1,8 +1,20 @@
 #!/bin/sh
 #
-# Copyright (c) 2021: Jacob.Lundqvist@gmail.com 2021-04-05
+# Copyright (c) 2021: Jacob.Lundqvist@gmail.com 2021-04-13
 # License: MIT
-# Version: 0.3.3 2021-04-05
+#
+# Version: 0.3.5 2021-04-13
+#                Refactored task_restore_root_home & task_restore_user
+#                to use a common function for restoring home_dir and
+#                extracting tarballs into a tmpdir, so that if extract fails
+#                it can be removed with no ill effect on the intended home_dir
+#          0.3.4 2021-04-09
+#                Refactored task_sshd with propper usage of openrc
+#                and possibility to select sshd port from config file.
+#                In addition patching /lib/rc/sh/rc-cgroup.sh
+#                to get rid of constant /proc/filesystems error messages
+#                any time a service is started or stopped
+#          0.3.3 2021-04-05
 #                Added error check for task_install_my_software
 #                if apk add fails
 #          0.3.2 2021-03-29
@@ -58,6 +70,7 @@ function error_msg() {
     printf "\nERROR: $msg\n\n"
 
     if [ "$err_code" != "" ]; then
+	prepare_extract_location 1 # clear tmp extract dir
         exit $err_code
     fi
 }
@@ -106,14 +119,14 @@ function msg_1() {
 function msg_2() {
     local msg=$1
 
-    echo "===  $msg  ==="
+    echo "=== $msg ==="
 }
 
 
 function msg_3() {
     local msg=$1
 
-    echo "---  $msg  ---"
+    echo "--- $msg ---"
 }
 
 
@@ -123,6 +136,25 @@ function msg_3() {
 #     Path and param handling
 #
 #==========================================================
+
+function prepare_extract_location() {
+    local remove_space=$1
+
+    extract_location="/tmp/restore-ish-$$"
+    rm $extract_location -rf
+    case "$remove_space" in
+	"")
+	    mkdir -p $extract_location
+	    cd $extract_location
+	    ;;
+	"1")
+	    ;;
+	*)
+	    echo
+	    echo "ERROR: prepare_extract_location() accepted params: nothing|1"
+	    exit 1
+    esac
+}
 
 function expand_path() {
     #
@@ -246,9 +278,15 @@ function setup_environment() {
             error_msg "Invalid setting: activate_sshd_service=$activate_sshd_service\nValid options: -1 0 1" 1
     esac
 
-    if [ "$purge_root" = "" ] || [ "$purge_root" -ne 1 ]; then
-        purge_root=0
+    # Default sshd port
+    if [ "$sshd_port" = "" ]; then
+	sshd_port=1022
     fi
+
+    if [ "$root_replace" = "" ] || [ "$root_replace" -ne 1 ]; then
+        root_replace=0
+    fi
+
     #
     # Unset variables depending on others
     #
@@ -261,7 +299,7 @@ function setup_environment() {
 
 #==========================================================
 #
-#     Some things called more than once from the tasks
+#     Various
 #
 #==========================================================
 
@@ -273,34 +311,183 @@ function replace_default_fs_inittab() {
     local inittab
 
     if [ "$FileSystem" != "AOK" ]; then
-    msg_3 "/etc/inittab"
-        # Get rid of unused getty's
-        inittab=$DEPLOY_PATH/files/inittab-default-FS
-    echo "$inittab"
-    if [ ! $task_display -eq 1 ]; then
-            cp "$inittab" /etc/inittab
+	msg_3 "/etc/inittab"
+	# Get rid of unused getty's
+	inittab=$DEPLOY_PATH/files/inittab-default-FS
+	echo "$inittab"
+	if [ ! $task_display -eq 1 ]; then
+	    cp "$inittab" /etc/inittab
+	fi
     fi
-    fi
+}
+
+
+#
+# This hack prevents all iSH service start and stops shoving an error
+# about not finding /proc/filesystems iSH does not currently suppport
+# that part of /proc
+# This snippet does not require bash /bin/sh is enough.
+# Needs to be run as root, but since this script already has that
+# requirement it should be fine.
+#
+function patch_rc_cgroup_sh() {
+    local fname=/lib/rc/sh/rc-cgroup.sh
+    local fn_backup=${fname}.org
+
+    # line wrapped to avoid ridiculously long line
+    local func_name_line_no=$(grep -n "cgroup2_find_path()" $fname |
+				  cut --delimiter=":" --fields=1)
+    local insert_on_line=$((func_name_line_no+2))
+
+    # In order to exand tab below, through trial and error, I discovered
+    # double expanding it turned out to work. Do not ask me why...
+    local patch_line="\\treturn 0  # ** Hack for iSH by jaclu ***"
+
+    msg_3 "Examining if $fname needs patching"
+    
+    # check content of line
+    early_return=$(sed "$insert_on_line !d" $fname)
+
+    #
+    # Since bash most likely isn't available when this is first run,
+    # we have to make do with /bin/sh and do string match
+    #  using a case statement - argh...
+    #
+    case $early_return in
+	*"return 0"*)
+            msg_3 "Patch already applied"
+	    ;;
+        *)
+	    msg_3 "Patch beeing applied"
+	    echo "Making function cgroup2_find_path() always return 0"
+	    echo "Saving original file to $fn_backup"
+	    cp $fname $fn_backup
+
+	    # kind of RPN, end result is an empty line after the patch line.
+	    # and the patch ends up on the expected line so will be detected
+	    # on later runs of this
+	    sed -i "$insert_on_line i \ " $fname
+	    sed -i "$insert_on_line i \$patch_line" $fname
+	    
+	    msg_3 "Patch completed!"
+            ;;
+    esac
 }
 
 
 function ensure_user_shell_is_installed() {
     if [ $task_display -eq 1 ]; then
-        test -x $user_shell ||  printf "*** WARNING: $user_shell not found\n*** Make sure it gets installed!\n"
+        test -x $user_shell || error_msg "$user_shell not found\n>>> Make sure it gets installed!<<<\n"
     else
         test -x $user_shell || error_msg "INVALID SHELL: $user_shell" 1
     fi   
 }
 
 
-function is_root_home_restored() {
-    if [ "$root_home_dir_unpacked_ptr" != "" ] && test -f $root_home_dir_unpacked_ptr ; then
-        msg_3 "Already restored"
-        echo "Found: $root_home_dir_unpacked_ptr"
-        do_root_home_restore=0
+#
+#  Restore $home_dir unless $unpacked_ptr points to an existing file.
+#  If $save_current is 1, curent home dir is moved to $home_dir-OLD and
+#  always restored.
+#
+function unpack_home_dir() {
+    local username=$1
+    local home_dir=$2
+    local fname_tgz=$3
+    local unpacked_ptr=$4
+    local save_current=$5
+
+    # Initialized params
+    #echo "unpack_home_dir($username,$home_dir,$fname_tgz,$unpacked_ptr,$save_current)"
+
+    #
+    #  Param checks
+    #
+    # Some of the checks below are ignored when $task_display is 1 ie just inforoming what will happen
+    if [ "$username" = "" ]; then
+	error_msg "unpack_home_dir() no username given" 1
+    fi
+    if [ ! $task_display -eq 1 ] && [ "$(grep ^$username /etc/passwd | wc -l)" != "1" ]; then
+	error_msg "unpack_home_dir($username) - username not found in /etc/passwd" 1
+    fi
+    if [ "$home_dir" = "" ]; then
+        error_msg "unpack_home_dir() no home_dir given" 1
+    fi
+    if [ ! $task_display -eq 1 ] && [ ! -d "$home_dir" ]; then
+        error_msg "unpack_home_dir($username, $home_dir) - home_dir does not exist" 1
+    fi
+    if [ ! $task_display -eq 1 ] && [ "$(ls -ld $home_dir | awk '{print $3}')" != "$username" ]; then
+        error_msg "unpack_home_dir($username, $home_dir) - username does not own home_dir" 1
+    fi
+    if [ "$fname_tgz" = "" ] || [ "$fname_tgz" = "1" ]; then
+	error_msg "unpack_home_dir($username, $home_dir,) - No tar file to be extracted given" 1
+    fi
+    if ! test -f $fname_tgz ; then
+    	error_msg "tar file not found:\n[$fname_tgz]" 1
+    fi 
+    case "$unpacked_ptr" in
+	"0"|"1" )
+  	    # Not actual error, no unpacked_ptr given so save_current got shifted here"
+	    save_current=$unpacked_ptr
+	    unpacked_ptr=""
+ 	    ;;
+	*)
+	   
+    esac
+    [ "$save_current" != "1" ] && save_current=0
+    # Parsed, and in some cases reshuffeled params
+    #echo "unpack_home_dir($username,$home_dir,$fname_tgz,$unpacked_ptr,$save_current)"
+ 
+    #
+    #  Actual work starts
+    #
+    msg_2 "$msg_txt"
+    if [ $save_current -eq 1 ]; then
+	do_unpack=1 # always restore
     else
-        [ $task_display -eq 1 ] && msg_3 "Will be restored"
-        do_root_home_restore=1
+    	if test -f $unpacked_ptr && [ "$unpacked_ptr" != "" ] ; then
+            msg_3 "Already restored"
+            echo "Found: $unpacked_ptr"
+            do_unpack=0
+	else
+            do_unpack=1
+   	fi
+    fi
+    if [ $do_unpack -eq 1 ]; then
+        if [ $task_display -eq 1 ]; then
+	    msg_3 "Will be restored"
+ 	    echo "Using: $fname_tgz"
+	    if [ $save_current -eq 1 ]; then
+		msg_3 "Previous content will be moved to ${home_dir}-OLD"
+	    fi
+	else
+	    prepare_extract_location
+	    msg_3 "Extracting"
+	    echo $fname_tgz
+	    2> /dev/null tar xfz "$fname_tgz"
+	    if [ $? -ne 0 ]; then
+		error_msg "Failed to unpack tarball" 1
+	    fi
+	    if [ ! -d "$extract_location/$username" ]; then
+		error_msg "No $username top dir found in the tarfile!" 1
+	    elif [ "$(find . -maxdepth 1 | wc -l)" != "2" ]; then
+		# suspicious
+		error_msg "Content outside intended destination found, check the tarfile!" 1
+	    fi
+ 	    echo "Done"
+	    if [ $save_current -eq 1 ]; then
+		rm ${home_dir}-OLD -rf
+		mv $home_dir ${home_dir}-OLD
+		msg_3 "Previous content has been moved to ${home_dir}-OLD"
+		mv $username $home_dir
+	    else
+		msg_3 "Overwriting into current $home_dir"
+		cd $home_dir
+		cd ..
+		cp -a "$extract_location/$username" .
+	    fi
+            msg_3 "$home_dir restored"
+	    prepare_extract_location 1  # Remove tmp directory
+        fi
     fi
 }
 
@@ -454,7 +641,7 @@ function task_timezone() {
                 msg_3 "displaying time"
                 date
             else
-                error_msg "BAD TIMEZONE: $time_zone  ***" 1
+                error_msg "BAD TIMEZONE: $time_zone" 1
             fi
         fi
         echo
@@ -505,22 +692,14 @@ function task_sshd() {
         -1 ) # disable
             msg_2 "$msg_txt"
             msg_3 "will be disabled"
-            if [ ! $task_display -eq 1 ]; then
-                if [ "$FileSystem" = "AOK" ]; then
-                    if [ "$(2> /dev/null rc-status |grep sshd)" != "" ]; then
-                        msg_3 "AOK disable_sshd"
-                        disable_sshd
-                    else
-                        echo "no action needed"
-                    fi
+            if [ ! $task_display -eq 1 ]; then			
+                if [ "$(2> /dev/null rc-status |grep sshd)" != "" ]; then
+OA		    openrc default
+		    rc-service sshd stop
+        	    rc-update del sshd
+		    msg_3 "was disabled"
                 else
-                    if [ "$(grep sshd /etc/inittab)" != "" ]; then
-                        msg_3 "default FS disable sshd"
-                        2> /dev/null killall sshd
-                        replace_default_fs_inittab
-                    else
-                        echo "no action needed"
-                    fi
+                    echo "sshd not active, no action needed"
                 fi
             fi
             ;;
@@ -531,36 +710,27 @@ function task_sshd() {
             fi
 
             ;;
+	
         1 )  # activate 
             msg_2 "$msg_txt"
+	    if [ "$sshd_port" = "" ]; then
+		error_msg "Invalid setting: sshd_port must be specified" 1
+	    fi
             msg_3 "Will be enabled"
+	    # This will be run regardless if it was already running,
+	    # since the sshd_config might have changed
             if [ ! $task_display -eq 1 ]; then
-                if [ "$FileSystem" = "AOK" ]; then
-                    if [ "$(2> /dev/null rc-status |grep sshd)" = "" ]; then
-                        msg_3 "AOK enable_sshd"
-                        enable_sshd
-                    else
-                        echo "no action needed"
-                    fi
-                else
-                    apk add openssh-server openrc
-                    #rc-update add sshd
-
-                    msg_3 "Generating host keys if not present"
-                    echo "might take a while..."
-                    ssh-keygen -A
-                    echo
-
-                    if [ "$(grep -i 'port 1022' /etc/ssh/sshd_config)" = "" ]; then
-                        msg_3 "adding port 1022 to /etc/ssh/sshd_config"
-                        echo "Port 1022" >> /etc/ssh/sshd_config
-                    fi
-                    if [ "$(grep sshd /etc/inittab)" = "" ]; then
-                        msg_3 "adding sshd restart to /etc/inittab"
-                        echo "::sysinit:/etc/init.d/sshd restart" >> /etc/inittab
-                    fi
-                    msg_1 "sshd will start on next reboot"
-                fi
+		msg_3 "Installing openssh & openrc"
+		apk add openssh openrc
+		# use requested port
+		sed -i "s/.*Port.*/Port $sshd_port/" /etc/ssh/sshd_config
+		patch_rc_cgroup_sh
+		# activate service
+		openrc default
+		rc-update add sshd
+		# in case some config changes happened, make sure its restarted
+		rc-service sshd restart
+		msg_1 "sshd listening on port: $sshd_port"
             fi
             ;;
         *)
@@ -589,48 +759,25 @@ function task_nopasswd_sudo() {
 
 function task_restore_root_home() {
     local msg_txt="Restoration of /root"
-
+    local tar_test_result
+    
     if [ "$root_home_dir_tgz" != "" ]; then
-        msg_2 "$msg_txt"
-        if ! test -f $root_home_dir_tgz ; then
-            error_msg "Not found:\n$root_home_dir_tgz" 1
-        else
-            # [ $task_display -eq 1 ] || msg_3 "Found a tarball"
-            if [ $purge_root -eq 1 ]; then
-                if [ $task_display -eq 1 ]; then
-                    msg_3 "Will empty previous content"
-                else
-                    msg_3 "Removing all previous content"
-                    rm /root -rf
-                fi
-            else
-                is_root_home_restored
-            fi
-            if [ ! $task_display -eq 1 ]; then
-                if [ $do_root_home_restore -eq 1 ]; then
-                    msg_3 "Unpacking"
-                    echo "$root_home_dir_tgz"
-                    cd /
-                    tar xfz "$root_home_dir_tgz"
-                    msg_3 "/root restored"
-                fi
-            fi
-        fi
-        echo
-    elif [ $task_display -eq 1 ] &&  [ $display_non_tasks -eq 1 ]; then
-        msg_2 "$msg_txt"
-        echo "Will NOT restore any content"
-        echo
+	unpack_home_dir root /root $root_home_dir_tgz $root_home_dir_unpacked_ptr $root_replace
     fi
+    echo
 }
+
 
 function task_restore_user() {
     local msg_txt="Username: $my_uname"
     local user_shell=${my_shell:-/bin/ash}
 
     if [ "$my_uname" != "" ]; then
+	#
+	# Ensure user is created
+	#
         msg_2 "$msg_txt"
-        grep $my_uname /etc/passwd > /dev/null
+        grep ^$my_uname /etc/passwd > /dev/null
         if [ $? -eq 1 ]; then
             msg_3 "Will be created"
             msg_3 "shell: $user_shell"
@@ -653,37 +800,18 @@ function task_restore_user() {
             ensure_user_shell_is_installed
         fi
         echo
-
-        msg_txt="Restoration of /home/$my_uname"
-        if [ "$my_home_dir_tgz" != "" ]; then
-            msg_2 "$msg_txt"
-
-            test -f $my_home_dir_tgz || error_msg "Not found: $my_home_dir_tgz" 1
-            #[ $task_display -eq 1 ] || msg_3 "Found a tarball"
-            if [ "$my_home_dir_unpacked_ptr" != "" ] && test -f $my_home_dir_unpacked_ptr ; then
-                msg_3 "Already restored"
-                echo "Found: $my_home_dir_unpacked_ptr"
-            else
-                if [ $task_display -eq 1 ]; then
-                    msg_3 "Will be restored"
-                    echo "$my_home_dir_tgz"
-                else
-                    msg_3 "Unpacking"
-                    echo "$my_home_dir_tgz"
-                    cd /home
-                    tar xfz "$my_home_dir_tgz"
-                    msg_3 "/home/$my_uname restored"
-                fi
-            fi
-            echo
-        elif [ $task_display -eq 1 ] &&  [ $display_non_tasks -eq 1 ]; then
-            msg_2 "$msg_txt"
-            echo "Will NOT be done"
-        fi
+	
+   	#
+	# Restore user home
+	#
+	if [ "$my_home_dir_tgz" != "" ]; then
+            msg_txt="Restoration of /home/$my_uname"
+	    unpack_home_dir $my_uname /home/$my_uname "$my_home_dir_tgz" "$my_home_dir_unpacked_ptr"
+	fi
     elif [ $task_display -eq 1 ] &&  [ $display_non_tasks -eq 1 ]; then
         msg_2 "Will NOT create any user"
-        echo
     fi
+    echo
 }
 
 
@@ -741,17 +869,15 @@ function run_tasks() {
     # It is probably not a good idea to reshuffle their order too much
     # some of them depend on previous tasks
     #
-
     task_aok_tweaks
     task_replace_some_etc_files
 
     task_update
-
     # do before upgrade to avoid time waste of upgrading
     # only to then remove it
     task_remove_software
-
     task_upgrade
+
     task_install_my_software
     task_timezone
     task_ssh_host_keys
@@ -763,12 +889,11 @@ function run_tasks() {
     task_user_pw_reminder
 }
 
-wait_after_summary=5
 
 
 setup_environment
 
-
+wait_after_summary=5
 #
 # Display all tasks
 #
@@ -792,5 +917,8 @@ task_display=0
 msg_1 "Restore begins"
 run_tasks
 
+
+# Ensure tmp directory is gone
+prepare_extract_location 1
 
 msg_2 "All done, system restored!"
