some tweaks to the samples

diff --git a/samples/additional-restore-tasks b/samples/additional-restore-tasks
--- a/samples/additional-restore-tasks
+++ b/samples/additional-restore-tasks
@@ -1,35 +1,50 @@
-#!/bin/sh. 
+#!/bin/sh 
 
 #
-# Verifies my_uname has been set.
+#   sourced, so variables &ffunctions in restore-ish can be used.
 #
-#[ "$my_uname" == "" ] && error_msg "This additonal-restore-tasks can not run without a my_uname set!" 1
-
-#msg_2 "Doing some soft-links"
+#   This is just a sample, comment out or replacee to fit your needs.
 #
-#ln -sf /home/${my_uname}/git_repos/mine/tmux_common /usr/local
-#ln -sf /home/${my_uname}/git_repos/mine/shell_envs /usr/local
-#ln -sf /home/${my_uname}/git_repos/others/bash-git-prompt /usr/local
-#ln -sf /home/${my_uname}/git_repos/others/powerlevel10k /usr/local
-
-
-#msg_2 "Making path_modify.sh available"
-#echo "/usr/local/bin/path_modify.sh"
-#ln -sf /usr/local/shell_envs/scripts/path_modify.sh /usr/local/bin
-#echo
 
 
 #
-# If hostname script is found
+#   Verifies my_uname has been set, without it
+#   most of the rest would fail
 #
-#my_additional_stuff=$DEPLOY_PATH/custom/additional-as-$my_uname
-#if ! test -f $my_additional_stuff ; then
-#	error_msg "Not found: $my_additional_stuff"
-#elif test -x $my_additional_stuff ; then
-#    msg_1 "Running user-based extra script"
-#    echo "Script: $my_additional_stuff"
-#    echo
-#    /bin/su -c $my_additional_stuff - $my_uname
-#else
-#    error_msg "$my_additional_stuff is not a runable script!"
-#fi
+[ "$my_uname" == "" ] && error_msg "This additonal-restore-tasks can not run without a my_uname set!" 1
+
+
+#
+#   Set up some common softlinks
+#
+msg_2 "Creating common soft-links"
+ln -sf /home/${my_uname}/git_repos/mine/tmux_common /usr/local
+ln -sf /home/${my_uname}/git_repos/mine/shell_envs /usr/local
+ln -sf /home/${my_uname}/git_repos/others/bash-git-prompt /usr/local
+ln -sf /home/${my_uname}/git_repos/others/powerlevel10k /usr/local
+echo
+
+
+#
+#   Adding some stuff to /usr/local/bin
+#
+msg_2 "Adding to /usr/local/bin"
+msg_3 "path_modify.sh"
+ln -sf /usr/local/shell_envs/scripts/path_modify.sh /usr/local/bin
+echo
+
+
+#
+#   Run $my_uname script, if found
+#
+my_additional_stuff=$DEPLOY_PATH/custom/additional-as-$my_uname
+if ! test -f $my_additional_stuff ; then
+    error_msg "Not found: $my_additional_stuff"
+elif test -x $my_additional_stuff ; then
+    msg_1 "Running user-based extra script"
+    msg_2 "$my_additional_stuff"
+    echo
+    /bin/su -c $my_additional_stuff - $my_uname
+else
+    error_msg "$my_additional_stuff is not a runable script!"
+fi
